name: Maven Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run tests before packaging?"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Make checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build and Deploy
        run: mvn clean deploy --settings $GITHUB_WORKSPACE/settings.xml -DskipTests
